### ISSUE TITLE
ESM-IF1 installation 

### ISSUE THREAD

**Issue by sahakyanhk** [facebookresearch/esm#473]
**Bug description**
I am trying to install and run inverse folding. I started a new conda environment from scratch as recommended and installed the required packages. During the installation no issues were reported, but I got this CUDA compatibility issues: 

>>> import esm.inverse_folding
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/saakyanh2/miniconda3/envs/inverse/lib/python3.9/site-packages/esm/inverse_folding/__init__.py", line 6, in <module>
    from . import gvp_transformer
  File "/data/saakyanh2/miniconda3/envs/inverse/lib/python3.9/site-packages/esm/inverse_folding/gvp_transformer.py", line 16, in <module>
    from .features import DihedralFeatures
  File "/data/saakyanh2/miniconda3/envs/inverse/lib/python3.9/site-packages/esm/inverse_folding/features.py", line 73, in <module>
    from .gvp_modules import GVP, LayerNorm
  File "/data/saakyanh2/miniconda3/envs/inverse/lib/python3.9/site-packages/esm/inverse_folding/gvp_modules.py", line 33, in <module>
    from torch_geometric.nn import MessagePassing
  File "/data/saakyanh2/miniconda3/envs/inverse/lib/python3.9/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/data/saakyanh2/miniconda3/envs/inverse/lib/python3.9/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/data/saakyanh2/miniconda3/envs/inverse/lib/python3.9/site-packages/torch_geometric/data/data.py", line 20, in <module>
    from torch_sparse import SparseTensor
  File "/data/saakyanh2/miniconda3/envs/inverse/lib/python3.9/site-packages/torch_sparse/__init__.py", line 18, in <module>
    torch.ops.load_library(spec.origin)
  File "/data/saakyanh2/miniconda3/envs/inverse/lib/python3.9/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/data/saakyanh2/miniconda3/envs/inverse/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /gpfs/gsfs6/users/saakyanh2/miniconda3/envs/inverse/lib/python3.9/site-packages/torch_sparse/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

I was able to install the package on google colab but in that case, GPU was not supported.

**Comment by tomsercu** [comment]
Sounds like a pytorch cuda version mismatch, doesn't it come up even if you just initialize a torch tensor and move it to GPU?
In any case the place to look is for a mismatch between the cuda driver on your system being older than the cuda version you installed pytorch with; you should make a new conda environment and then carefully pick the pytorch installer matching your cuda version (which you can find out with a command like `nvcc --version`)

**Comment by KeaunAmani** [comment]
@tomsercu I'm currently getting the exact same error and I just tested the above with this code:
```py
print(device, flush=True)
print(torch.zeros(1,5).to(device), flush=True)
torch.zeros(1,5).to("cuda:0")
esm_if_model, esm_if_alphabet = esm.pretrained.esm_if1_gvp4_t16_142M_UR50()
```

That code returns this error:
```py
cuda:0
tensor([[0., 0., 0., 0., 0.]], device='cuda:0')
/home/.../.../.venv/lib/python3.9/site-packages/torch_geometric/typing.py:18: UserWarning: An issue occurred while importing 'pyg-lib'. Disabling its usage. Stacktrace: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory
  warnings.warn(f"An issue occurred while importing 'pyg-lib'. "
/home/.../.../.venv/lib/python3.9/site-packages/torch_geometric/typing.py:31: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: /home/.../.../.venv/lib/python3.9/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
  warnings.warn(f"An issue occurred while importing 'torch-scatter'. "
/home/.../.../.venv/lib/python3.9/site-packages/torch_geometric/typing.py:42: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: /home/.../.../.venv/lib/python3.9/site-packages/torch_sparse/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
  warnings.warn(f"An issue occurred while importing 'torch-sparse'. "
Traceback (most recent call last):
  File "/home/.../.../test.py", line 234, in <module>
    esm_if_model, esm_if_alphabet = esm.pretrained.esm_if1_gvp4_t16_142M_UR50()
  File "/home/.../.../.venv/lib/python3.9/site-packages/esm/pretrained.py", line 347, in esm_if1_gvp4_t16_142M_UR50
    return load_model_and_alphabet_hub("esm_if1_gvp4_t16_142M_UR50")
  File "/home/.../.../.venv/lib/python3.9/site-packages/esm/pretrained.py", line 64, in load_model_and_alphabet_hub
    return load_model_and_alphabet_core(model_name, model_data, regression_data)
  File "/home/.../.../.venv/lib/python3.9/site-packages/esm/pretrained.py", line 193, in load_model_and_alphabet_core
    model, alphabet, model_state = _load_model_and_alphabet_core_v1(model_data)
  File "/home/.../.../.venv/lib/python3.9/site-packages/esm/pretrained.py", line 129, in _load_model_and_alphabet_core_v1
    import esm.inverse_folding
  File "/home/.../.../.venv/lib/python3.9/site-packages/esm/inverse_folding/__init__.py", line 6, in <module>
    from . import gvp_transformer
  File "/home/.../.../.venv/lib/python3.9/site-packages/esm/inverse_folding/gvp_transformer.py", line 16, in <module>
    from .features import DihedralFeatures
  File "/home/.../.../.venv/lib/python3.9/site-packages/esm/inverse_folding/features.py", line 73, in <module>
    from .gvp_modules import GVP, LayerNorm
  File "/home/.../.../.venv/lib/python3.9/site-packages/esm/inverse_folding/gvp_modules.py", line 33, in <module>
    from torch_geometric.nn import MessagePassing
  File "/home/.../.../.venv/lib/python3.9/site-packages/torch_geometric/__init__.py", line 1, in <module>
    import torch_geometric.utils
  File "/home/.../.../.venv/lib/python3.9/site-packages/torch_geometric/utils/__init__.py", line 8, in <module>
    from .dropout import dropout_adj, dropout_node, dropout_edge, dropout_path
  File "/home/.../.../.venv/lib/python3.9/site-packages/torch_geometric/utils/dropout.py", line 6, in <module>
    import torch_cluster  # noqa
  File "/home/.../.../.venv/lib/python3.9/site-packages/torch_cluster/__init__.py", line 18, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/.../.../.venv/lib/python3.9/site-packages/torch/_ops.py", line 573, in load_library
    ctypes.CDLL(path)
  File "/cvmfs/.../easybuild/software/2020/avx2/Core/python/3.9.6/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/.../.../.venv/lib/python3.9/site-packages/torch_cluster/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs
```
