### ISSUE TITLE
'GVPTransformerModel' object has no attribute 'num_layers'

### ISSUE THREAD

**Issue by bg-uni** [facebookresearch/esm#501]
Hello,
I have a question.

en I run the script as follows, I get an error.

<script>
python3 extract.py  esm_if1_gvp4_t16_142M_UR50 ./../../data/fast_max5_only_seq.list ./../../output_512 --include per_tok
./../../data/fast_max5_only_seq.list -> Input file
./../../output_512　-> output folder

<error>
/home/ubuntu/my_singularity/ProtTrans/workspace/daimon/src/esm-main/esm/pretrained.py:215: UserWarning: Regression weights not found, predicting contacts will not produce correct results.
  warnings.warn(
Transferred model to GPU
Read ../../data/fast_max5_only_seq.list with 0 sequences
Traceback (most recent call last):
  File "/home/ubuntu/my_singularity/ProtTrans/workspace/daimon/src/esm-main/extract.py", line 137, in <module>
    main(args)
  File "/home/ubuntu/my_singularity/ProtTrans/workspace/daimon/src/esm-main/extract.py", line 84, in main
    assert all(-(model.num_layers + 1) <= i <= model.num_layers for i in args.repr_layers)
  File "/home/ubuntu/my_singularity/ProtTrans/workspace/daimon/src/esm-main/extract.py", line 84, in <genexpr>
    assert all(-(model.num_layers + 1) <= i <= model.num_layers for i in args.repr_layers)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GVPTransformerModel' object has no attribute 'num_layers'

Can you please tell me the cause?
Thanks for your help!

**Comment by naailkhan28** [comment]
Looks like you're trying to use `extract.py` with ESM-IF which isn't supported - `extract.py` is used for obtaining embeddings from the ESM language models.

Also, I think the input file is supposed to be in FASTA format as well.
