### ISSUE TITLE
'esm-fold' error from command line execution

### ISSUE THREAD

**Issue by amoroso2** [facebookresearch/esm#521]
I really appreciate ESMfold in this field.
I was able to run my python file without any problem of installing 'openfold'.
However, when I executed esm-fold using my fasta file by command line, I ended up with  "ModuleNotFoundError: No module named 'openfold'" as follow.
I would be very grateful to any suggestions to solve this issue.
Thank you very much for your help in advance.
================================
(esmfold) administrator@XXXXX:~/esm$ esm-fold -i ~/esm/test_sequence.fasta -o ~/esm/ --chunk-size 32
23/04/07 20:28:17 | INFO | root | Reading sequences from /home/administrator/esm/test_sequence.fasta
23/04/07 20:28:17 | INFO | root | Loaded 1 sequences from /home/administrator/esm/test_sequence.fasta
23/04/07 20:28:17 | INFO | root | Loading model
Traceback (most recent call last):
  File "/home/administrator/.local/bin/esm-fold", line 8, in <module>
    sys.exit(main())
  File "/home/administrator/.local/lib/python3.8/site-packages/esm/scripts/fold.py", line 197, in main
    run(args)
  File "/home/administrator/.local/lib/python3.8/site-packages/esm/scripts/fold.py", line 138, in run
    model = esm.pretrained.esmfold_v1()
  File "/home/administrator/.local/lib/python3.8/site-packages/esm/pretrained.py", line 419, in esmfold_v1
    import esm.esmfold.v1.pretrained
  File "/home/administrator/.local/lib/python3.8/site-packages/esm/esmfold/v1/pretrained.py", line 5, in <module>
    from esm.esmfold.v1.esmfold import ESMFold
  File "/home/administrator/.local/lib/python3.8/site-packages/esm/esmfold/v1/esmfold.py", line 17, in <module>
    from esm.esmfold.v1.misc import (
  File "/home/administrator/.local/lib/python3.8/site-packages/esm/esmfold/v1/misc.py", line 12, in <module>
    from openfold.np import residue_constants
ModuleNotFoundError: No module named 'openfold'

**Comment by MaoSihong** [comment]
as you can see, there are no openfold on your local machine as esm-fold dependancy
