### ISSUE TITLE
RuntimeError 

### ISSUE THREAD

**Issue by tonyageall** [facebookresearch/esm#670]
I'm using Pytorch CPU-only, on a ubuntu 18 OS.  I'm trying to run ESM-fold. I'm getting the following error:

RuntimeError: Keys 'trunk.structure_module.ipa.linear_kv_points.linear.bias, tru                                                                                                 nk.structure_module.ipa.linear_q_points.linear.weight, trunk.structure_module.ip                                                                                                 a.linear_q_points.linear.bias, trunk.structure_module.ipa.linear_kv_points.linea                                                                                                 r.weight' are missing.

Is this an issue with Pytorch? Or some other dependency?

**Comment by Floboysky** [comment]
Hi everyone, first thanks for your work!

I have the same problem as @tonyageall. This error indicates a problem with the structure of the neural network. There is no correspondence between the keys expected, and the keys found by the downloaded model. I try with different models but, I have the same error. How can we fix that? Can anyone help us?

Thanks for your answers.

**Comment by Ming-Qin-tech** [comment]
same question

**Comment by YanggjCode** [comment]
I also have the same problems ,by use cuda 11.8 torch 2.0.0 openfold 2.0 
import esm
import torch
model = esm.pretrained.esmfold_v1()
###################################
RuntimeError: Keys 'trunk.structure_module.ipa.linear_q_points.linear.weight, trunk.structure_module.ipa.linear_kv_points.linear.bias, trunk.structure_module.ipa.linear_q_points.linear.bias, trunk.structure_module.ipa.linear_kv_points.linear.weight' are missing.

Thanks for your answers.

**Comment by Arkadiy-Garber** [comment]
Same issue:

```
Traceback (most recent call last):
  File "./esm-fold.py", line 5, in <module>
    model = esm.pretrained.esmfold_v1()
  File "/home/ark/miniconda3/envs/esmfold3/lib/python3.7/site-packages/esm/pretrained.py", line 420, in esmfold_v1
    return esm.esmfold.v1.pretrained.esmfold_v1()
  File "/home/ark/miniconda3/envs/esmfold3/lib/python3.7/site-packages/esm/esmfold/v1/pretrained.py", line 54, in esmfold_v1
    return _load_model("esmfold_3B_v1")
  File "/home/ark/miniconda3/envs/esmfold3/lib/python3.7/site-packages/esm/esmfold/v1/pretrained.py", line 29, in _load_model
    raise RuntimeError(f"Keys '{', '.join(missing_essential_keys)}' are missing.")
RuntimeError: Keys 'trunk.structure_module.ipa.linear_q_points.linear.bias, trunk.structure_module.ipa.linear_kv_points.linear.bias, trunk.structure_module.ipa.linear_kv_points.linear.weight, trunk.structure_module.ipa.linear_q_points.linear.weight' are missing.
```

**Comment by WrViajreo** [comment]
You may refer to [issue: 435](https://github.com/facebookresearch/esm/issues/435) for any specific solutions.
