### ISSUE TITLE
[Question] AssertionError using extract.py

### ISSUE THREAD

**Issue by JinyuanSun** [facebookresearch/esm#77]
Hello, I was trying to use
```bash
python extract.py esm1b_t33_650M_UR50S ../test/test.fasta my_reprs/ --repr_layers 0 32 33 --include mean per_tok
```
And it returns:

```python
Traceback (most recent call last):
  File "extract.py", line 134, in <module>
    main(args)
  File "extract.py", line 66, in main
    dataset = FastaBatchedDataset.from_file(args.fasta_file)
  File "/home/jsun/msa_transformer/esm/esm/data.py", line 52, in from_file
    assert len(set(sequence_labels)) == len(sequence_labels)
AssertionError
```
I guess that there are problems with my fasta file (about 350 sequences and 450 amino acids for each). Are there any restrictions on fasta file? Can anyone please help me with this problem?

**Comment by JinyuanSun** [comment]
I found duplicated accessions in my fasta file and caused this error.
